name: MovingMountainsDriver
options:
  bundleIdPrefix: com.movingmountains
  deploymentTarget:
    iOS: 15.0
targets:
  MovingMountainsDriver:
    type: application
    platform: iOS
    sources: 
      - MovingMountainsDriver
    info:
      path: MovingMountainsDriver/Info.plist
      properties:
        CFBundleDisplayName: "Driver App"
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
